changing the DQ map to be updated at the end of find_bad_pixels
kammerje/spaceKLIP pull request #226
Opened 2024-10-28 16:23 UTC by strampelligiovanni

2024-10-30 20:41 UTC, AarynnCarter requested changes

2024-10-30 20:41 UTC, AarynnCarter commented on spaceKLIP/imagetools.py
> +
Okay I think I understand this now, but what's confusing me is why this isn't captured by the `'dqarr'` method on line 1024. Ideally I think we should give people the option to use the default DO_NOT_USE flags or not, which is what this should do. 

Do you see different results between the current implementation and the old implementation when specifying dq_arr?

2024-11-04 21:44 UTC, strampelligiovanni commented on spaceKLIP/imagetools.py
> +
So, I did some testing and I don't see differences when I use the dqarr compare to when I don't. In both cases, if I use the previous version of the code, there are still some elements in the DQ that are not caputerd at the end. 
Also in the dqarr the DO_NOT_USE flags is never called so I'm not sure how this should have worked.

2024-11-27 15:20 UTC, AarynnCarter approved these changes

2024-11-27 16:31 UTC, merged